spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.100/gulimall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:
      seata:
        tx-service-group: gulimall-order-fescar-service-group
  application:
      name: gulimall-order
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.100
  session:
    store-type: redis
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss


  zipkin:
    base-url: http://192.168.56.100:9411
    sender:
      type: web
    discovery-client-enabled: false # 取消nacos对zipkin的服务发现
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000

feign:
  sentinel:
    enabled: true
# ThreadPool配置
gulimall:
    thread:
      core-pool-size: 20
      maximum-pool-size: 200
      keep-alive-time: 10
      unit: seconds

logging:
  level:
    com.shilin.gulimall.order: debug
    com.alibaba.nacos.client.*: WARN






























