spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8008
  application:
    name: gulimall-auth
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.100
    port: 6379
  session:
    store-type: redis
  zipkin:
    base-url: http://192.168.56.100:9411
    sender:
      type: web
    discovery-client-enabled: false # 取消nacos对zipkin的服务发现
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1

server:
  port: 20000
  servlet:
    session:
      timeout: 30m
logging:
  level:
    com.alibaba.nacos.client.*: WARN

management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  sentinel:
    enabled: true
